services:
  - type: web
    name: ignaciocordoba-backend
    env: python
    region: oregon
    plan: free
    branch: main
    
    rootDir: backend
    
    buildCommand: |
      cd src
      pip install --upgrade pip
      pip install -r ../requirements.txt
    
    startCommand: cd src && python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    
    envVars:
      - key: ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 23707
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://drhernanignaciocordoba.me
      - key: BACKEND_URL
        value: https://ignaciocordoba-backend.onrender.com